core:
  project_path: /home/jiucheng/data/sk_data
  sample_fold_path: /data/RawData/cffDNA/2020-11-03/X101SC20091348-Z01/20201104_HJVN5DSXY-X101SC20091348-Z01_Result/Rawdata

biosoft:
  fastp: /biosoftware/bin/fastp
  bwa: /biosoftware/bin/bwa
  samtools: /biosoftware/bin/samtools

database:
  reference: /data/Database/index/hg19/hg19.fa

samples:
  F10: 20201030-SNP-pool1-20201020-F10_L1_1.fq.gz
  P11: 20201030-SNP-pool1-20201020-F2_L1_1.fq.gz

